---
- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present
- name: Configure UFW defaults
  community.general.ufw:
    direction: incoming
    policy: deny
- name: Allow SSH
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp
  notify: restart ufw
- name: Secure SSH config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  loop:
    - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no' }
    - { regexp: '^PermitRootLogin', line: 'PermitRootLogin no' }
  notify: restart ssh
