- name: Add Flathub remote
  command: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
  become: false

- name: Install Discord via Flatpak
  community.general.flatpak:
    name: com.discordapp.Discord
    state: present
    remote: flathub